"""Content production pipeline orchestration."""

from dataclasses import dataclass
from typing import List

from .agent import ContentRequest, InteractiveAgent


@dataclass(frozen=True)
class ContentPiece:
    """Content piece generated by the pipeline."""

    model_id: str
    theme: str
    prompt: str


class BoudoirPipeline:
    """Autonomous boudoir content production pipeline."""

    def __init__(self, agent: InteractiveAgent) -> None:
        self._agent = agent

    def generate_batch(
        self, requests: List[ContentRequest]
    ) -> List[ContentPiece]:
        """Generates a batch of content pieces.

        Args:
            requests: List of content requests.

        Returns:
            List of generated content pieces.
        """
        pieces: List[ContentPiece] = []
        for request in requests:
            prompt = self._agent.build_prompt(request)
            pieces.append(
                ContentPiece(
                    model_id=request.model_id,
                    theme=request.theme,
                    prompt=prompt,
                )
            )
        return pieces

    def generate_for_all_models(self, theme: str, mood: str) -> List[ContentPiece]:
        """Generates a content piece for each available model.

        Args:
            theme: Session theme.
            mood: Desired emotional tone.

        Returns:
            List of content pieces, one per model.
        """
        requests = [
            ContentRequest(
                model_id=model.id,
                theme=theme,
                mood=mood,
                extras=[],
            )
            for model in self._agent.available_models()
        ]
        return self.generate_batch(requests)
